### ISSUE TITLE
ng中的关键性词汇是否要翻译？

### ISSUE THREAD

**Issue by twinstony** [chylvina/ng-book-translation#1]
比如Module，Filter等等

**Comment by chylvina** [comment]
拿不准的专有名字先放着就行，以后统一替换，不过Module和filter我翻译了。

**Comment by twinstony** [comment]
单独提出一份常见的通用词汇表，统一出口吧。

**Comment by chylvina** [comment]
是的后续会做
2014-2-28 PM11:03于 "twinstony" notifications@github.com写道：

**Comment by chylvina** [comment]
增加了 Conventions.md 作为翻译约定文件。
