### ISSUE TITLE
翻译时,"we"用什么样的称谓？

### ISSUE THREAD

**Issue by chaoren1641** [chylvina/ng-book-translation#8]
比方说这句话

`If we are planning release our applications for Internet Explorer v8.0 or earlier, we need to pay some
extra attention to help support it.`

翻译出来可能是：
`如果我们想在IE8之前的浏览器中运行AngularJS，我们需要一些额外的支持。`

也可能是
`如果大家想在IE8之前的浏览器中运行AngularJS，我们需要一些额外的支持。`

**Comment by chylvina** [comment]
现在我看到的几个人用的都是我们，包括我自己。

**Comment by miclay** [comment]
我觉得用“我们”就行，有的情况可以适当省略。中国话省略代词很多见，比如：Are you ready？就译成“准备好了吗”
